@extends('layout')
@section('title','news1')
@section('container')
@parent
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Amet nisl purus in mollis nunc sed. Quisque id diam vel quam elementum pulvinar etiam. Non quam lacus suspendisse faucibus interdum posuere lorem. Sed risus pretium quam vulputate dignissim suspendisse. Morbi tincidunt ornare massa eget egestas purus viverra accumsan in. Rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis. Tincidunt augue interdum velit euismod in pellentesque. Lectus mauris ultrices eros in cursus turpis massa. Cras tincidunt lobortis feugiat vivamus at augue eget arcu. Pretium quam vulputate dignissim suspendisse in est. Elit sed vulputate mi sit amet mauris commodo quis. Eget egestas purus viverra accumsan in. Habitant morbi tristique senectus et netus.

Cursus sit amet dictum sit amet justo donec. Id interdum velit laoreet id donec ultrices tincidunt. Mi tempus imperdiet nulla malesuada pellentesque elit eget. Odio morbi quis commodo odio aenean sed adipiscing diam donec. A lacus vestibulum sed arcu non odio euismod lacinia. Tincidunt dui ut ornare lectus sit amet est. Habitant morbi tristique senectus et netus et malesuada. Elit at imperdiet dui accumsan. Enim ut tellus elementum sagittis. Diam quis enim lobortis scelerisque fermentum dui faucibus in ornare. Mauris in aliquam sem fringilla ut morbi tincidunt. Venenatis lectus magna fringilla urna porttitor. Elementum eu facilisis sed odio. Vitae elementum curabitur vitae nunc sed velit. In cursus turpis massa tincidunt dui.

Amet commodo nulla facilisi nullam vehicula. Et molestie ac feugiat sed lectus vestibulum mattis. Quam nulla porttitor massa id neque. Dolor magna eget est lorem ipsum dolor sit. Elementum tempus egestas sed sed risus pretium quam. Quis risus sed vulputate odio ut enim blandit volutpat maecenas. Lobortis elementum nibh tellus molestie nunc non. Ac ut consequat semper viverra. Nulla pellentesque dignissim enim sit amet. Malesuada fames ac turpis egestas maecenas pharetra convallis. Quam vulputate dignissim suspendisse in est ante in nibh mauris. Dignissim cras tincidunt lobortis feugiat vivamus at augue eget. Pharetra et ultrices neque ornare aenean euismod elementum nisi. In pellentesque massa placerat duis ultricies lacus sed. Viverra vitae congue eu consequat ac felis donec. Tempus iaculis urna id volutpat lacus laoreet non curabitur gravida. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet.

Pharetra diam sit amet nisl suscipit. Nisl pretium fusce id velit ut tortor. Vestibulum lorem sed risus ultricies tristique nulla aliquet. Sollicitudin tempor id eu nisl. Nulla pellentesque dignissim enim sit. Molestie at elementum eu facilisis sed odio morbi quis. Elit sed vulputate mi sit amet mauris. Velit ut tortor pretium viverra suspendisse potenti nullam ac. In mollis nunc sed id. Dictum fusce ut placerat orci nulla. Pretium fusce id velit ut. Cursus turpis massa tincidunt dui. Maecenas ultricies mi eget mauris pharetra et ultrices.

Mauris sit amet massa vitae tortor condimentum. Amet risus nullam eget felis eget. At elementum eu facilisis sed. Bibendum arcu vitae elementum curabitur vitae nunc sed. Ullamcorper velit sed ullamcorper morbi. Ut enim blandit volutpat maecenas volutpat. Orci eu lobortis elementum nibh tellus molestie. Odio aenean sed adipiscing diam donec adipiscing tristique. Orci a scelerisque purus semper eget. Suspendisse interdum consectetur libero id faucibus nisl. Sagittis vitae et leo duis ut diam quam nulla. At lectus urna duis convallis convallis tellus. Vel risus commodo viverra maecenas accumsan. Risus quis varius quam quisque id diam vel quam. Massa enim nec dui nunc mattis enim ut tellus.</p>

@endsection
<h1>news1</h1>
